### ISSUE TITLE
Channel misconfigured [TypeError, require(...) is not a function] from v11.7.1

### ISSUE THREAD

**Issue by 3bu1** [botpress/v12#660]
* I am running: `Botpress server 11.7.4`
* My OS is: `ubuntu 18.04 & Windows 10 Pro`

Hi team,
Facebook channel messenger is throwing `Channel misconfigured [TypeError, require(...) is not a function]` from v11.7.1 version, also checked in v11.7.4 in both linux and windows operating systmes, still the same issue. But same code works fine in 11.6.3. Attached screenshot. 

Kindly help with this. We are about to buy license. 

![image](https://user-images.githubusercontent.com/6350331/55478852-51ae9a80-563a-11e9-8aed-b9537aa52985.png)
