### ISSUE TITLE
[Bug] bp push crash after upgrade to 12.18.2

### ISSUE THREAD

**Issue by robertoandrade** [botpress/v12#1281]
**Describe the bug**
When running `bp push` on a brand new installation of 12.18.2 the command crashes right away with an error that a `common/auth` module can't be found.

**To Reproduce**

1. Run `docker run botpress/server:v12_18_2 ./bp push`
2. See error

```
root@4ad357de287a:/botpress# ./bp push
Error starting botpress
Error: Cannot find module 'common/auth'
Require stack:
- /snapshot/build-linux/out/bp/bpfs.js
- /snapshot/build-linux/out/bp/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/snapshot/build-linux/out/bp/bpfs.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.handler (/snapshot/build-linux/out/bp/index.js)
    at Object.runCommand (/snapshot/build-linux/node_modules/yargs/build/index.cjs:424:48) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/build-linux/out/bp/bpfs.js',
    '/snapshot/build-linux/out/bp/index.js'
  ],
  pkg: true
}
Cannot find module 'common/auth'
Require stack:
- /snapshot/build-linux/out/bp/bpfs.js
- /snapshot/build-linux/out/bp/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
---STACK---
Error: Cannot find module 'common/auth'
Require stack:
- /snapshot/build-linux/out/bp/bpfs.js
- /snapshot/build-linux/out/bp/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/snapshot/build-linux/out/bp/bpfs.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.handler (/snapshot/build-linux/out/bp/index.js)
    at Object.runCommand (/snapshot/build-linux/node_modules/yargs/build/index.cjs:424:48)
```

**Expected behavior**
Push command to return usage or start the push normally.

**Screenshots**

**Environment (please complete the following information):**

- OS: macOS
- Botpress Version: 12.18.2
- NodeJS: 14.4.0

**Additional context**
Seems like the problem has been happening since the 12.18.1 release since it runs on 12.17.2 and 12.18.0 without issues.
